Lifebuoy/Lifebuoy/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lifebuoy.DAL;
using Lifebuoy.Models;
using System.Net;

namespace Lifebuoy.Controllers
{
    public class CatalogController : Controller
    {
        private OffersContext db = new OffersContext();
        private OffersContext db1 = new OffersContext();
        private ApplicationDbContext adb = new ApplicationDbContext();

        public ActionResult Index(string categories, string providers, string cities)
        {

            ViewBag.SkinDetails = db.SkinsDetails.ToList();
            IQueryable<Offers> offers = db.Offers;
            List<Offers> moderatedOffers = new List<Offers>();
            List<int> offIds = new List<int>();
            var mOffers = db.ModeratedOffers;
            foreach ( var q in mOffers)
            {
                offIds.Add(q.OfferId);
            }
           
            foreach (var q in offIds)
            {
                var offer = offers.FirstOrDefault(o => o.Id == q);
                if(offer!=null)
                    moderatedOffers.Add(offer);
            }

            offers = moderatedOffers.AsQueryable();

            if (!String.IsNullOrEmpty(categories)&&!categories.Equals("Не выбрано"))
            {
                offers = offers.Where(o => o.Category == categories);               
            }

            if (!String.IsNullOrEmpty(providers) && !providers.Equals("Не выбрано"))
            {
                offers = offers.Where(o => o.Provider == providers);
            }

            if (!String.IsNullOrEmpty(cities) && !cities.Equals("Не выбрано"))
            {
                offers = offers.Where(o => o.City == cities);
            }

            var city = db.Offers
              .OrderBy(c => c.City)
              .Select(c => c.City).Distinct().ToList();

            var category =  offers
                .OrderBy(c => c.Category)
                .Select(c => c.Category).Distinct().ToList();

            var provider = offers
                .OrderBy(c => c.Provider)
                .Select(c => c.Provider).Distinct().ToList();



            city.Insert(0, "Не выбрано");
            provider.Insert(0, "Не выбрано");
            category.Insert(0, "Не выбрано");
            offers = offers.OrderByDescending(o => o.Rating);

            OffersListView olv = new OffersListView
            {
                Offers = offers.ToList(),

                Categories = new SelectList(category),

                Providers = new SelectList(provider),

                Cities = new SelectList(city)

            };

            return View(olv);
        }

        public ActionResult ShowOffer(int? id)
        {
            List<String> Images = new List<string>();
            string[] splitResult;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offers offer = db.Offers.Find(id);
            splitResult = offer.Images.Split(';');
            Images = splitResult.ToList();
            Images.RemoveAt(Images.Count - 1);
            if (offer == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Images = Images;
            ViewBag.SkinDetails = db.SkinsDetails.FirstOrDefault(sk => sk.OfferId == id);

            return View(offer);
        }

        [HttpPost]
        public ActionResult SendRating(int id, int rating)
        {
            if(User.Identity.IsAuthenticated)
            {
                var userVote = db.UsersVotes.FirstOrDefault(uv => uv.UserName == User.Identity.Name & uv.OfferId == id);
                if (userVote == null)
                {
                    var offer = db.Offers.Find(id);
                    if (offer != null)
                    {
                        if (offer.Rating == 0)
                        {
                            offer.Rating = rating;
                        }
                        else
                            offer.Rating = Convert.ToInt32(Math.Ceiling(Convert.ToDouble((offer.Rating + rating) / 2)));

                        db.UsersVotes.Add(new UsersVotes { OfferId = id, UserName = User.Identity.Name });
                        offer.VotesCount += 1;
                        db.SaveChanges();
                        return Json(new { success = true, responseText = "Ваш голос учтён." }, JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json(new { success = false, responseText = "Призошла ошибка." }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    return Json(new { success = false, responseText = "Вы уже голосовали." }, JsonRequestBehavior.AllowGet);
                }
            }
            else
                return Json(new { success = false, responseText = "Авторизуйтесь для голосования" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddReview(int OfferId, string name, string title, string review)
        {
            db.UsersReviews.Add(new Reviews { OfferId = OfferId, UserId = User.Identity.Name, Review = review, Author = name, Title = title, Date = DateTime.Now});
            db.SaveChanges();

            var reviews = db.UsersReviews.Where(rv => rv.OfferId == OfferId)
                .OrderByDescending(rv => rv.Date)
                .ToList();
            return PartialView("AddReview",reviews);
        }

        public ActionResult LoadReviews(int id)
        {
            var reviews = db.UsersReviews.Where(rv => rv.OfferId == id)
                 .OrderByDescending(rv => rv.Date)
                 .ToList();
            return PartialView("AddReview", reviews);
        }

        public ActionResult DeleteReview (int id)
        {
            var review = db.UsersReviews.Find(id);
            if (review != null)
            {
                var offerId = review.OfferId;
                db.UsersReviews.Remove(review);
                db.SaveChanges();

                return RedirectToAction("ShowOffer", new { id = offerId });
            }
            else
                return HttpNotFound();

        }
    }
}

Lifebuoy/Lifebuoy/Controllers/ConstructorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lifebuoy.DAL;
using Lifebuoy.Models;
using System.IO;
using System.Drawing;

namespace Lifebuoy.Controllers
{
    public class ConstructorController : Controller
    {
        private OffersContext db = new OffersContext();

        public ActionResult Dashboard()
        {
              if(User.IsInRole("Provider"))
                {
                    var userName = User.Identity.Name;
                    IQueryable<ProvidersOffers> providerOffers = db.ProviderOffers;
                    List<Offers> offers = new List<Offers>();
                    List<int> offIds = new List<int>();

                    providerOffers = providerOffers.Where(o => o.Owner == User.Identity.Name);
                    foreach (var q in providerOffers)
                    {
                        offIds.Add(q.OfferId);
                    }

                    foreach (var q in offIds)
                    {
                        var offer = db.Offers.FirstOrDefault(o => o.Id == q);
                        if (offer != null)
                            offers.Add(offer);
                    }

                    return View(offers);
                }
                else
                    return View("AccessDenied");
        }
        [HttpGet]
        public ActionResult SkinSettings(int? id)
        {
            List<String> Images = new List<string>();
            string[] splitResult;

            var offer = db.Offers.Find(id);
            if (offer!=null)
            {
                splitResult = offer.Images.Split(';');
                Images = splitResult.ToList();
                Images.RemoveAt(Images.Count - 1);
                ViewBag.Images = Images;

                return View(offer);
            }
                
            else
                return HttpNotFound();
        }
   
         [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SkinSettings(FormCollection fc)
         {
            string photo_Display_Type = fc.Get("pic");
            string background = fc.Get("backgr");
            string hot = fc.Get("hot");
            string hightlight = fc.Get("hightlight");
            int offerId = Convert.ToInt32(fc.Get("offerId"));
            var sd = db.SkinsDetails.FirstOrDefault(d => d.OfferId == offerId);
            if (sd == null)
            {
                db.SkinsDetails.Add(new SkinDetails
                {
                    photoDisplayMode = photo_Display_Type,
                    background = background,
                    hotOffer = hot,
                    hightlight = hightlight,
                    OfferId = offerId
                });
            }
            else
            { 
                sd.photoDisplayMode = photo_Display_Type;
                sd.background = background;
                sd.hotOffer = hot;
                sd.hightlight = hightlight;
                sd.OfferId = offerId;
            }
            db.SaveChanges();
            return RedirectToAction("Dashboard");
         }

        public ActionResult Details(int? id)
        {
            if (User.IsInRole("Provider"))
            {
                if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                Offers offers = db.Offers.Find(id);
                if (offers == null)
                    {
                        return HttpNotFound();
                    }
                return View(offers);
            }
            else
                return View("AccessDenied");
        }

        public ActionResult FillData()
        {
            if (User.IsInRole("Provider"))
            {
                return View();
            }
            else
                return View("AccessDenied");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FillData(IEnumerable<HttpPostedFileBase> files, Offers offers)
        {
            if (User.IsInRole("Provider"))
            {
                if (ModelState.IsValid)
                {
                    string images = "";

                    if (files != null)
                    foreach (var file in files)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            byte[] imageData = null;
                            using (var binaryReader = new BinaryReader(file.InputStream))
                            {
                                imageData = binaryReader.ReadBytes(file.ContentLength);
                            }
                            images += Convert.ToBase64String(imageData) + ";";
                        }
                    }
                    var id = offers.Provider.Split('@')[0] + "_" + offers.Category+"_" + offers.CatalogName;
                    offers.catalogID = Transliter.GetTranslit(id);
                    offers.Images = images;
                    db.Offers.Add(offers);
                    db.SaveChanges();
                    db.ProviderOffers.Add(new ProvidersOffers { OfferId = offers.Id, Owner = User.Identity.Name });
                    db.SaveChanges();
                    return RedirectToAction("Dashboard");
                }
                return View(offers);
            }
            else
                return View("AccessDenied");
        }

        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("Provider"))
            {
                List<String> Images = new List<string>();
                string[] splitResult;
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Offers offers = db.Offers.Find(id);
                if (offers == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    splitResult = offers.Images.Split(';');
                    Images = splitResult.ToList();
                    Images.RemoveAt(Images.Count - 1);
                }
                ViewBag.Images = Images;
                return View(offers);
            }
            else
                return View("AccessDenied");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IEnumerable<HttpPostedFileBase> files, Offers offers)
        {
            if (User.IsInRole("Provider"))
            {
                if (ModelState.IsValid)
                {
                    var item = db.Offers.FirstOrDefault(c => c.Id == offers.Id);
                    string images = "";

                    if (files != null)
                    {
                        foreach (var file in files)
                        {
                            if (file != null && file.ContentLength > 0)
                            {
                                byte[] imageData = null;
                                using (var binaryReader = new BinaryReader(file.InputStream))
                                {
                                    imageData = binaryReader.ReadBytes(file.ContentLength);
                                }
                                images += Convert.ToBase64String(imageData) + ";";
                            }
                        }
                    }

                    item.Id = offers.Id;
                    item.Adress = offers.Adress;
                    item.catalogID = offers.catalogID;
                    item.CatalogImg = offers.CatalogImg;              
                    item.CatalogName = offers.CatalogName;
                    item.Category = offers.Category;
                    item.City = offers.City;
                    item.Contacts = offers.Contacts;
                    item.Description = offers.Description;
                    item.Provider = offers.Provider;
                    item.Prices = offers.Prices;
                    item.Rating = offers.Rating;
                    item.ShortDescription = offers.ShortDescription;
                    item.WorkingHours = offers.WorkingHours;
                    item.isModerated = false;
                    var tmp = db.ModeratedOffers.FirstOrDefault(o => o.OfferId == item.Id);
                    if(tmp!=null)
                        db.ModeratedOffers.Remove(tmp);

                    db.SaveChanges();
                    return RedirectToAction("Dashboard");
                }
            return View(offers);
            }
            else
                return View("AccessDenied");
        }

        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("Provider"))
            {
                List<String> Images = new List<string>();
                string[] splitResult;
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Offers offers = db.Offers.Find(id);
                if (offers == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    splitResult = offers.Images.Split(';');
                    Images = splitResult.ToList();
                    Images.RemoveAt(Images.Count - 1);
                }
                ViewBag.Images = Images;
                return View(offers);
            }
            else
                return View("AccessDenied");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (User.IsInRole("Provider"))
            {
                Offers offers = db.Offers.Find(id);

Lifebuoy/Lifebuoy/Views/Shared/AccessDenied.cshtml
<html>
<head>
    <title>401 Недостаточно прав</title>
</head>
<body class="error-bckgr">
    <div class="row error-row">
        <h2>401 Недостаточно прав</h2>
        <hr />
        <p>К сожалению, запрашиваемая Вами страница вам не доступна. Обратитесь к администратору</p>
        <p>Почему?</p>
        <ol>
            <li>Изменение роли ещё не вступило в силу. Попробуйте перезайти в аккаунт.
            <li>Возможно вам не хватает прав для просмотра этой страницы.
            <li>Проверьте правильность ссылки.
        </ol>
        <p>Вернуться на <a href="@Url.Action("Index", "Home")">главную.</a></p>
    </div>
</body>
</html>

Lifebuoy/Lifebuoy/Views/Shared/AddReview.cshtml
@model IEnumerable<Lifebuoy.Models.Reviews>
@if(Model.Count() == 0)
{
    <p>У этого предложения ещё нет отзывов</p>
}
else { 
foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <span itemscope="" itemtype="http://schema.org/Review">
                <h3 class="panel-title" itemprop="name"><b>@item.Title</b></h3>
            </span>
        </div>
        <div class="panel-body" itemprop="reviewBody">
            <p>
                @item.Review
            </p>

            <span itemprop="author" itemscope="" itemtype="http://schema.org/Person">
                <small>
                    <span itemprop="name">@item.Author</span>
                </small>
            </span><!--/author schema -->
            <small>
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                <meta itemprop="datePublished" content=@item.Date.ToShortDateString()>@item.Date.ToShortDateString()
            </small>
            @if ((Request.IsAuthenticated && item.UserId == User.Identity.Name) || User.IsInRole("Moderator"))
            {
                <div>
                    <a class="catalog-link" href="@Url.Action("DeleteReview","Catalog", new { id = item.Id })">Удалить</a>
                </div>
            }
            
        </div>
    </div>
}
}

Lifebuoy/Lifebuoy/Views/Shared/_CatalogLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Scada" rel="stylesheet">
</head>
<body id="catalog_body" class="constr-bckgr">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/Content/images/logo.png" class="logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Каталог", "Index", "Catalog")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Provider"))
                    {
                        <li>@Html.ActionLink("Конструктор", "Dashboard", "Constructor")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Moderator"))
                    {
                        <li>@Html.ActionLink("Панель модератора", "ModeratorPage", "Admin")</li>
                    }  
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Панель администратора", "AdministratorPage", "Admin")</li>
                    }  
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="catalog-container body-content">
        <div class="row">
            <div class="col-md-2 ">
                <div class="catalog-sidebar affix">
                    @Html.Partial("_CatalogSidebarPartial")
                </div>
                <!--/sidebar-nav-fixed -->
            </div>
            <!--/span-->
            <div class="col-md-10 sidebar-divider">
                @RenderBody()
            </div>
        </div>


        @*<div class="row">
            <hr />
            <footer id="footer">
                <p>&copy; @DateTime.Now.Year - LifeBuoy</p>
            </footer>
        </div>*@
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lifebuoy/Lifebuoy/Views/Shared/_CatalogOfferLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/Scripts/jquery-1.8.3.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=PT+Serif|Poiret+One&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Scada" rel="stylesheet">
</head>
<body id="offer_body" class="constr-bckgr">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/Content/images/logo.png" class="logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Каталог", "Index", "Catalog")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Provider"))
                    {
                        <li>@Html.ActionLink("Конструктор", "Dashboard", "Constructor")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Moderator"))
                    {
                        <li>@Html.ActionLink("Панель модератора", "ModeratorPage", "Admin")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Панель администратора", "AdministratorPage", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div>
            <footer>
                <p>&copy; @DateTime.Now.Year - LifeBuoy</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lifebuoy/Lifebuoy/Views/Shared/_ConstructorLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/Scripts/jquery-1.8.3.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=PT+Serif|Poiret+One&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Scada" rel="stylesheet">
</head>
<body id="constr_body" class="constr-bckgr">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/Content/images/logo.png" class="logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Каталог", "Index", "Catalog")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Provider"))
                    {
                        <li>@Html.ActionLink("Конструктор", "Dashboard", "Constructor")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Moderator"))
                    {
                        <li>@Html.ActionLink("Панель модератора", "ModeratorPage", "Admin")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Панель администратора", "AdministratorPage", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div>
            @RenderBody()
        </div>
        <div>
            @Html.Partial("_ConstructorSidebar")
        </div>

        @*<hr />
        <div>
            <footer>
                <p>&copy; @DateTime.Now.Year - LifeBuoy</p>
            </footer>
        </div>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lifebuoy/Lifebuoy/Views/Shared/_ConstructorSidebar.cshtml
@using (Html.BeginForm("SkinSettings", "Constructor", FormMethod.Post))
{   
<div class="constructor-sidebar" >
    <input type="text" id="offerId" name="offerId" style="visibility:hidden" />
    <div class="const-sbar-row">
        <p class="const-section-name">Отображение фотографий</p>
        <div class="radio">
            <label><input type="radio" name="pic" value="carusel" checked />Карусель</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="pic" value="gallery" />Галерея</label>
        </div>
    </div>
    <div class="const-sbar-row">
        <p class="const-section-name">Фоновое изображение</p>
        <div class="radio">
            <label><input type="radio" name="fon" checked value="empty" />Без фона</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="fon" value="pic" />Картинка</label>
        </div>
        <div class="form-group">
            <input type='file' id='verborgen_file' name="background" />
            <input type="text" id="backgr" name="backgr" style="visibility:hidden" />
            <input type="button" value="Загрузить" disabled id="uploadButton" />
        </div>
    </div> 
    <div class="const-sbar-row">
        <p class="const-section-name">Дополнительные функции</p>
        <div class="checkbox">
            <label><input type="checkbox" id="hot" name="hot" value="hot" />Поле "Горячее предложение"</label>
        </div>
        <div class="checkbox">
            <label><input type="checkbox" id="hightlight" name="hightlight" value="hightlight" />Выделение при серьёзном обновлении</label>
        </div>
    </div>   
    <div class="const-sbar-row">         
        <div class="form-group">
            <input type="submit" class="btn btn-success btn-md" value="Отправить" />
            <input type="reset" class="btn btn-danger btn-md" value="Очистить" />
            @Html.ActionLink("Назад", "Dashboard",new { },new {@class = "btn btn-info" })
        </div>  
    </div> 

</div>
@Html.AntiForgeryToken()
}

Lifebuoy/Lifebuoy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/Scripts/jquery-1.8.3.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=PT+Serif|Poiret+One&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Scada" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/Content/images/logo.png" class="logo" />
                </a>                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Каталог", "Index", "Catalog")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Provider"))
                    {
                        <li>@Html.ActionLink("Конструктор", "Dashboard", "Constructor")</li>
                    }
                    @if(Request.IsAuthenticated && User.IsInRole("Moderator"))
                    {
                    <li>@Html.ActionLink("Панель модератора", "ModeratorPage", "Admin")</li>   
                    }  
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    { 
                    <li>@Html.ActionLink("Панель администратора", "AdministratorPage", "Admin")</li>   
                    }          
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div>
            <footer>
                <p>&copy; @DateTime.Now.Year - LifeBuoy</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>